# 测试环境配置
# 数据库配置
spring.datasource.url=jdbc:mysql://localhost:3306/mgtt?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=test
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 初始化器配置
mgtt.data.initialize=true