CREATE TABLE IF NOT EXISTS api_audit_log (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL,
    user_id INT NULL,
    http_method VARCHAR(16) NOT NULL,
    path VARCHAR(255) NOT NULL,
    http_status INT NOT NULL,
    biz_code INT NULL,
    success TINYINT(1) NOT NULL DEFAULT 0,
    latency_ms BIGINT NOT NULL DEFAULT 0,
    client_ip VARCHAR(64) NULL,
    user_agent VARCHAR(255) NULL,
    request LONGTEXT NULL,
    response LONGTEXT NULL,
    error TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_api_audit_log_request_id (request_id),
    KEY idx_api_audit_log_user_id (user_id),
    KEY idx_api_audit_log_http_method (http_method),
    KEY idx_api_audit_log_path (path),
    KEY idx_api_audit_log_http_status (http_status),
    KEY idx_api_audit_log_biz_code (biz_code),
    KEY idx_api_audit_log_success (success),
    KEY idx_api_audit_log_latency_ms (latency_ms),
    KEY idx_api_audit_log_client_ip (client_ip),
    KEY idx_api_audit_log_created_at (created_at)
);
