server:
  port: 8080
  mode: debug

database:
  host: 10.199.203.199
  port: 3306
  username: mango_crew
  password: GNeAnc5ZrsQa3xbj
  database: mango_crew
  max_idle_conns: 10
  max_open_conns: 100

log:
  level: debug
  format: console
  output: stdout

wechat:
  login_url: https://api.weixin.qq.com/sns/jscode2session

storage:
  upload_dir: ./avatars
  public_path: /avatars
