server:
  port: 8080
  mode: debug

database:
  host: 192.168.1.113
  port: 3306
  username: root
  password: mysql_zZSRc6
  database: mgtt
  max_idle_conns: 10
  max_open_conns: 100

log:
  level: debug
  format: console
  output: stdout

wechat:
  login_url: https://api.weixin.qq.com/sns/jscode2session
