server:
  port: 8080
  mode: release

database:
  host: 1Panel-mysql-I81e
  port: 3306
  username: mango_crew
  password: mysql_zZSRc6
  database: mango_crew
  max_idle_conns: 10
  max_open_conns: 100

log:
  level: info
  format: json
  output: stdout

wechat:
  login_url: https://api.weixin.qq.com/sns/jscode2session
